### ISSUE TITLE
Addon Doesn't work on Kodi!

### ISSUE THREAD

**Issue by player7000000** [DxCx/plugin.video.wonderfulsubs#100]
I have tried reaching out on Reddit but no help. I have uninstalled and reinstalled both Kodi and the Wonderful Subs addon multiple times on my Firestick. Wonderful Subs is completely blank on my end. I can't even search anime by name. Please help! The Wonderful Subs version is 0.0.23 and was installed through the GitHub Browser.

**Comment by doko-desuka** [comment]
Without more details (like your Kodi log) there's no way to say what error is going on.
One of these days the website was giving a Cloudflare 502 error, and it's now been fixed. Please try again and see if the add-on is working again. It is here on my end (2019-07-26).
