### ISSUE TITLE
HLS does not seem to work recently

### ISSUE THREAD

**Issue by sq01neo** [DxCx/plugin.video.wonderfulsubs#109]
I've tested it on Android and PC version of Kodi. Kodi version 18.4 with inputstream adaptive version 2.4.2 (Windows) and version 2.3.22 (Android)

**Comment by sq01neo** [comment]
nvm, it looks like this is limited to specific episodes.

**Comment by doko-desuka** [comment]
What series was it?  
I noticed the same on `Astra - Lost in Space`, the HLS source led to a 404.
