### ISSUE TITLE
Is this dead? I can't do anything.

### ISSUE THREAD

**Issue by Freelancer95** [DxCx/plugin.video.wonderfulsubs#132]
Can't get logs due to not knowing where the heck they are through ADBLink.

**Comment by Freelancer95** [comment]
16:36:41.326 T:18446744071737616672  NOTICE: special://profile/ is mapped to: special://masterprofile/
16:36:41.326 T:18446744071737616672  NOTICE: -----------------------------------------------------------------------
16:36:41.326 T:18446744071737616672  NOTICE: Starting Kodi (17.6 Git:20171114-a9a7a20). Platform: Android ARM 32-bit
16:36:41.326 T:18446744071737616672  NOTICE: Using Release Kodi x32 build
16:36:41.327 T:18446744071737616672  NOTICE: Kodi compiled Nov 14 2017 by GCC 4.9.0 for Android ARM 32-bit API level 21 (API level 21)
16:36:41.327 T:18446744071737616672  NOTICE: Running on Amazon AFTMM with Android 7.1.2 API level 25, kernel: Linux ARM 32-bit version 4.4.120+
16:36:41.327 T:18446744071737616672  NOTICE: FFmpeg version/source: ffmpeg-3.1-kodi
16:36:41.327 T:18446744071737616672  NOTICE: Host CPU: ARMv7 Processor rev 4 (v7l), 4 cores available
16:36:41.327 T:18446744071737616672  NOTICE: Product: mantis, Device: mantis, Board: mantis - Manufacturer: Amazon, Brand: Amazon, Model: AFTMM, Hardware: mt8695
16:36:41.331 T:18446744071737616672  NOTICE: External storage path = /storage/emulated/0; status = ok
16:36:41.331 T:18446744071737616672  NOTICE: ARM Features: Neon enabled
16:36:41.331 T:18446744071737616672  NOTICE: special://xbmc/ is mapped to: /data/user/0/org.xbmc.kodi/cache/apk/assets
16:36:41.331 T:18446744071737616672  NOTICE: special://xbmcbin/ is mapped to: /data/user/0/org.xbmc.kodi/cache/apk/assets
16:36:41.331 T:18446744071737616672  NOTICE: special://xbmcbinaddons/ is mapped to: /data/app/org.xbmc.kodi-1/lib/arm
16:36:41.331 T:18446744071737616672  NOTICE: special://masterprofile/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata
16:36:41.331 T:18446744071737616672  NOTICE: special://envhome/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files
16:36:41.331 T:18446744071737616672  NOTICE: special://home/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi
16:36:41.331 T:18446744071737616672  NOTICE: special://temp/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp
16:36:41.331 T:18446744071737616672  NOTICE: special://logpath/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp
16:36:41.332 T:18446744071737616672  NOTICE: The executable running is: /data/app/org.xbmc.kodi-1/lib/arm/libkodi.so
16:36:41.332 T:18446744071737616672  NOTICE: Local hostname: localhost
16:36:41.332 T:18446744071737616672  NOTICE: Log File is located: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp//kodi.log
16:36:41.332 T:18446744071737616672  NOTICE: -----------------------------------------------------------------------
16:36:41.333 T:18446744071737616672  NOTICE: load settings...
16:36:41.358 T:18446744071737616672   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/settings.xml
16:36:41.361 T:18446744071737616672 WARNING: CSettingInt: unknown options filler "audiocdactions" of "audiocds.autoaction"
16:36:41.380 T:18446744071737616672   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/android.xml
16:36:41.406 T:18446744071737616672  NOTICE: Float is supported
16:36:41.407 T:18446744071737616672   DEBUG: AESinkAUDIOTRACK - 32000 supported
16:36:41.408 T:18446744071737616672   DEBUG: AESinkAUDIOTRACK - 44100 supported
16:36:41.408 T:18446744071737616672   DEBUG: AESinkAUDIOTRACK - 48000 supported
16:36:41.410 T:18446744071737616672   DEBUG: AESinkAUDIOTRACK - 88200 supported
16:36:41.411 T:18446744071737616672   DEBUG: AESinkAUDIOTRACK - 96000 supported
16:36:41.412 T:18446744071737616672   DEBUG: AESinkAUDIOTRACK - 176400 supported
16:36:41.413 T:18446744071737616672   DEBUG: AESinkAUDIOTRACK - 192000 supported
16:36:41.428 T:18446744071737616672   DEBUG: Firmware implements AC3 RAW
16:36:41.455 T:18446744071737616672   DEBUG: Firmware implements EAC3 RAW
16:36:41.478 T:18446744071737616672  NOTICE: Found 1 Lists of Devices
16:36:41.478 T:18446744071737616672  NOTICE: Enumerated AUDIOTRACK devices:
16:36:41.478 T:18446744071737616672  NOTICE:     Device 1
16:36:41.478 T:18446744071737616672  NOTICE:         m_deviceName      : AudioTrack
16:36:41.478 T:18446744071737616672  NOTICE:         m_displayName     : android
16:36:41.478 T:18446744071737616672  NOTICE:         m_displayNameExtra: audiotrack
16:36:41.478 T:18446744071737616672  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
16:36:41.479 T:18446744071737616672  NOTICE:         m_channels        : FL,FR,FC,LFE,SL,SR,BL,BR,BC,BLOC,BROC
16:36:41.479 T:18446744071737616672  NOTICE:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
16:36:41.479 T:18446744071737616672  NOTICE:         m_dataFormats     : AE_FMT_S16LE,AE_FMT_FLOAT,AE_FMT_RAW
16:36:41.479 T:18446744071737616672  NOTICE:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_EAC3
16:36:41.489 T:18446744071737616672   DEBUG: CSkinSettings: no <skinsettings> tag found
16:36:41.490 T:18446744071737616672  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
16:36:41.490 T:18446744071737616672  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
16:36:41.490 T:18446744071737616672  NOTICE: Default Video Player: VideoPlayer
16:36:41.490 T:18446744071737616672  NOTICE: Default Audio Player: paplayer
16:36:41.490 T:18446744071737616672  NOTICE: Disabled debug logging due to GUI setting. Level 0.
16:36:41.490 T:18446744071737616672  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
16:36:41.491 T:18446744071737616672  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
16:36:41.497 T:18446744071737616672  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
16:36:41.498 T:18446744071737616672  NOTICE: Loaded playercorefactory configuration
16:36:41.498 T:18446744071737616672  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
16:36:41.499 T:18446744071737616672  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
16:36:41.525 T:18446744071737616672  NOTICE: Running database version Addons27
16:36:41.695 T:18446744071737616672  NOTICE: ADDONS: Using repository repository.xbmc.org
16:36:41.695 T:18446744071737616672  NOTICE: ADDONS: Using repository superrepo.kodi.krypton.all
16:36:41.695 T:18446744071737616672  NOTICE: ADDONS: Using repository repository.exodusredux
16:36:41.695 T:18446744071737616672  NOTICE: ADDONS: Using repository repo.plugin.video.9anime
16:36:41.695 T:18446744071737616672  NOTICE: ADDONS: Using repository repository.kodil
16:36:41.695 T:18446744071737616672  NOTICE: ADDONS: Using repository repository.ptom
16:36:41.695 T:18446744071737616672  NOTICE: ADDONS: Using repository repository.venom
16:36:41.841 T:18446744071720401184  NOTICE: Trying to open: 44100 samplerate 12 channelMask 4 encoding
16:36:41.847 T:18446744071720401184  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 22688 m_frames: 1418 m_frameSize: 8 channels: 2
16:36:41.890 T:18446744071737616672  NOTICE: InitWindowSystem: Using EGL Implementation: android
16:36:41.905 T:18446744071737616672  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 59.939999 Hz
16:36:41.905 T:18446744071737616672  NOTICE: Found (1280x720@59.939999) at 16, setting to RES_DESKTOP at 16
16:36:41.905 T:18446744071737616672  NOTICE: Checking resolution 16
16:36:41.923 T:18446744071737616672  NOTICE: GL_VENDOR = Imagination Technologies
16:36:41.924 T:18446744071737616672  NOTICE: GL_RENDERER = PowerVR Rogue GE8300
16:36:41.924 T:18446744071737616672  NOTICE: GL_VERSION = OpenGL ES 3.2 build 1.9@4893595
16:36:41.924 T:18446744071737616672  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 3.20 build 1.9@4893595
16:36:41.924 T:18446744071737616672  NOTICE: GL_EXTENSIONS = GL_EXT_debug_marker GL_ANDROID_extension_pack_es31a GL_EXT_blend_minmax GL_EXT_buffer_storage GL_EXT_clear_texture GL_EXT_color_buffer_float GL_EXT_conservative_depth GL_EXT_copy_image GL_EXT_discard_framebuffer GL_EXT_draw_buffers GL_EXT_draw_buffers_indexed GL_EXT_draw_elements_base_vertex GL_EXT_float_blend GL_EXT_geometry_point_size GL_EXT_geometry_shader GL_EXT_gpu_shader5 GL_EXT_multi_draw_arrays GL_EXT_multisampled_render_to_texture GL_EXT_occlusion_query_boolean GL_EXT_polygon_offset_clamp GL_EXT_primitive_bounding_box GL_EXT_pvrtc_sRGB GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_separate_shader_objects GL_EXT_shader_framebuffer_fetch GL_EXT_shader_group_vote GL_EXT_shader_io_blocks GL_EXT_shader_non_constant_global_initializers GL_EXT_shader_pixel_local_storage GL_EXT_shader_pixel_local_storage2 GL_EXT_shader_texture_lod GL_EXT_shadow_samplers GL_EXT_sparse_texture GL_EXT_sRGB_write_control GL_EXT_tessellation_point_size GL_EXT_tessellation_shader GL_EXT_texture_border_clamp GL_EXT_texture_buffer GL_EXT_texture_cube_map_array GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_EXT_YUV_target GL_IMG_bindless_texture GL_IMG_framebuffer_downsample GL_IMG_multisampled_render_to_texture GL_IMG_program_binary GL_IMG_read_format GL_IMG_shader_binary GL_IMG_texture_compression_pvrtc GL_IMG_texture_compression_pvrtc2 GL_IMG_texture_format_BGRA8888 GL_IMG_texture_npot GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_depth_texture GL_OES_draw_buffers_indexed GL_OES_draw_elements_base_vertex GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_element_index_uint GL_OES_fragment_precision_high GL_OES_geometry_point_size GL_OES_geometry_shader GL_OES_get_program_binary GL_OES_gpu_shader5 GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_required_internalformat GL_OES_rgb8_rgba8 GL_OES_sample_shading GL_OES_sample_variables GL_OES_shader_image_atomic GL_OES_shader_io_blocks GL_OES_shader_multisample_interpolation GL_OES_standard_derivatives GL_OES_surfaceless_context GL_OES_tessellation_point_size GL_OES_tessellation_shader GL_OES_texture_border_clamp GL_OES_texture_buffer GL_OES_texture_cube_map_array GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_npot GL_OES_texture_stencil8 GL_OES_texture_storage_multisample_2d_array GL_OES_vertex_array_object GL_OES_vertex_half_float GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture
16:36:42.467 T:18446744071727024416  NOTICE: Running database version Addons27
16:36:42.469 T:18446744071727024416  NOTICE: Running database version ViewModes6
16:36:42.472 T:18446744071727024416  NOTICE: Running database version Textures13
16:36:42.478 T:18446744071727024416  NOTICE: Running database version MyMusic60
16:36:42.491 T:18446744071727024416  NOTICE: Running database version MyVideos107
16:36:42.497 T:18446744071727024416  NOTICE: Running database version TV29
16:36:42.501 T:18446744071727024416  NOTICE: Running database version Epg11
16:36:42.947 T:18446744071737616672 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
16:36:43.693 T:18446744071737616672  NOTICE: initialize done
16:36:43.693 T:18446744071737616672  NOTICE: Running the application...
16:36:43.695 T:18446744071737616672  NOTICE: starting upnp client
16:36:43.709 T:18446744071737616672  NOTICE: GL_VENDOR = Imagination Technologies
16:36:43.710 T:18446744071737616672  NOTICE: GL_RENDERER = PowerVR Rogue GE8300
16:36:43.710 T:18446744071737616672  NOTICE: GL_VERSION = OpenGL ES 3.2 build 1.9@4893595
16:36:43.710 T:18446744071737616672  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 3.20 build 1.9@4893595
16:36:43.710 T:18446744071737616672  NOTICE: GL_EXTENSIONS = GL_EXT_debug_marker GL_ANDROID_extension_pack_es31a GL_EXT_blend_minmax GL_EXT_buffer_storage GL_EXT_clear_texture GL_EXT_color_buffer_float GL_EXT_conservative_depth GL_EXT_copy_image GL_EXT_discard_framebuffer GL_EXT_draw_buffers GL_EXT_draw_buffers_indexed GL_EXT_draw_elements_base_vertex GL_EXT_float_blend GL_EXT_geometry_point_size GL_EXT_geometry_shader GL_EXT_gpu_shader5 GL_EXT_multi_draw_arrays GL_EXT_multisampled_render_to_texture GL_EXT_occlusion_query_boolean GL_EXT_polygon_offset_clamp GL_EXT_primitive_bounding_box GL_EXT_pvrtc_sRGB GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_separate_shader_objects GL_EXT_shader_framebuffer_fetch GL_EXT_shader_group_vote GL_EXT_shader_io_blocks GL_EXT_shader_non_constant_global_initializers GL_EXT_shader_pixel_local_storage GL_EXT_shader_pixel_local_storage2 GL_EXT_shader_texture_lod GL_EXT_shadow_samplers GL_EXT_sparse_texture GL_EXT_sRGB_write_control GL_EXT_tessellation_point_size GL_EXT_tessellation_shader GL_EXT_texture_border_clamp GL_EXT_texture_buffer GL_EXT_texture_cube_map_array GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_EXT_YUV_target GL_IMG_bindless_texture GL_IMG_framebuffer_downsample GL_IMG_multisampled_render_to_texture GL_IMG_program_binary GL_IMG_read_format GL_IMG_shader_binary GL_IMG_texture_compression_pvrtc GL_IMG_texture_compression_pvrtc2 GL_IMG_texture_format_BGRA8888 GL_IMG_texture_npot GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_depth_texture GL_OES_draw_buffers_indexed GL_OES_draw_elements_base_vertex GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_element_index_uint GL_OES_fragment_precision_high GL_OES_geometry_point_size GL_OES_geometry_shader GL_OES_get_program_binary GL_OES_gpu_shader5 GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_required_internalformat GL_OES_rgb8_rgba8 GL_OES_sample_shading GL_OES_sample_variables GL_OES_shader_image_atomic GL_OES_shader_io_blocks GL_OES_shader_multisample_interpolation GL_OES_standard_derivatives GL_OES_surfaceless_context GL_OES_tessellation_point_size GL_OES_tessellation_shader GL_OES_texture_border_clamp GL_OES_texture_buffer GL_OES_texture_cube_map_array GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_npot GL_OES_texture_stencil8 GL_OES_texture_storage_multisample_2d_array GL_OES_vertex_array_object GL_OES_vertex_half_float GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture
16:36:43.719 T:18446744071737616672  NOTICE: GL_VENDOR = Imagination Technologies
16:36:43.719 T:18446744071737616672  NOTICE: GL_RENDERER = PowerVR Rogue GE8300
16:36:43.719 T:18446744071737616672  NOTICE: GL_VERSION = OpenGL ES 3.2 build 1.9@4893595
16:36:43.719 T:18446744071737616672  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 3.20 build 1.9@4893595
16:36:43.719 T:18446744071737616672  NOTICE: GL_EXTENSIONS = GL_EXT_debug_marker GL_ANDROID_extension_pack_es31a GL_EXT_blend_minmax GL_EXT_buffer_storage GL_EXT_clear_texture GL_EXT_color_buffer_float GL_EXT_conservative_depth GL_EXT_copy_image GL_EXT_discard_framebuffer GL_EXT_draw_buffers GL_EXT_draw_buffers_indexed GL_EXT_draw_elements_base_vertex GL_EXT_float_blend GL_EXT_geometry_point_size GL_EXT_geometry_shader GL_EXT_gpu_shader5 GL_EXT_multi_draw_arrays GL_EXT_multisampled_render_to_texture GL_EXT_occlusion_query_boolean GL_EXT_polygon_offset_clamp GL_EXT_primitive_bounding_box GL_EXT_pvrtc_sRGB GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_separate_shader_objects GL_EXT_shader_framebuffer_fetch GL_EXT_shader_group_vote GL_EXT_shader_io_blocks GL_EXT_shader_non_constant_global_initializers GL_EXT_shader_pixel_local_storage GL_EXT_shader_pixel_local_storage2 GL_EXT_shader_texture_lod GL_EXT_shadow_samplers GL_EXT_sparse_texture GL_EXT_sRGB_write_control GL_EXT_tessellation_point_size GL_EXT_tessellation_shader GL_EXT_texture_border_clamp GL_EXT_texture_buffer GL_EXT_texture_cube_map_array GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_EXT_YUV_target GL_IMG_bindless_texture GL_IMG_framebuffer_downsample GL_IMG_multisampled_render_to_texture GL_IMG_program_binary GL_IMG_read_format GL_IMG_shader_binary GL_IMG_texture_compression_pvrtc GL_IMG_texture_compression_pvrtc2 GL_IMG_texture_format_BGRA8888 GL_IMG_texture_npot GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_depth_texture GL_OES_draw_buffers_indexed GL_OES_draw_elements_base_vertex GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_element_index_uint GL_OES_fragment_precision_high GL_OES_geometry_point_size GL_OES_geometry_shader GL_OES_get_program_binary GL_OES_gpu_shader5 GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_required_internalformat GL_OES_rgb8_rgba8 GL_OES_sample_shading GL_OES_sample_variables GL_OES_shader_image_atomic GL_OES_shader_io_blocks GL_OES_shader_multisample_interpolation GL_OES_standard_derivatives GL_OES_surfaceless_context GL_OES_tessellation_point_size GL_OES_tessellation_shader GL_OES_texture_border_clamp GL_OES_texture_buffer GL_OES_texture_cube_map_array GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_npot GL_OES_texture_stencil8 GL_OES_texture_storage_multisample_2d_array GL_OES_vertex_array_object GL_OES_vertex_half_float GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture
16:36:43.726 T:18446744071621425440  NOTICE: ES: Starting UDP Event server on port 9777
16:36:43.727 T:18446744071621425440  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
16:36:44.286 T:18446744071651723552   ERROR: DoWork - Direct texture file loading failed for androidapp://sources/apps/com.amazon.ftv.screensaver.png
16:36:46.244 T:18446744071720401184  NOTICE: Trying to open: 44100 samplerate 12 channelMask 4 encoding
16:36:46.253 T:18446744071720401184  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 22688 m_frames: 1418 m_frameSize: 8 channels: 2
16:36:58.494 T:18446744071606630688 WARNING: CSkinInfo: failed to load skin settings
16:37:19.331 T:18446744071727024416   ERROR: GetDirectory - Error getting
16:37:28.158 T:18446744071619336480   ERROR: Previous line repeats 6 times.
16:37:28.158 T:18446744071619336480   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.wonderfulsubs/default.py", line 292, in <module>
                                                router_process(control.get_plugin_url(), control.get_plugin_params())
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.wonderfulsubs/resources/lib/ui/router.py", line 68, in router_process
                                                return route_obj.func(payload, params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.wonderfulsubs/default.py", line 230, in SEARCH_PAGES
                                                return control.draw_items(_BROWSER.search_site(query, int(page)), draw_cm=draw_cm)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.wonderfulsubs/resources/lib/WonderfulSubsBrowser.py", line 289, in search_site
                                                return self._process_anime_view(url, data, "search/%s/%%d" % search_string, page)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.wonderfulsubs/resources/lib/WonderfulSubsBrowser.py", line 107, in _process_anime_view
                                                json_resp = self._json_request(url, data)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.wonderfulsubs/resources/lib/WonderfulSubsBrowser.py", line 98, in _json_request
                                                response = json.loads(self._get_request(url, data))
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
16:37:28.327 T:18446744071737616672   ERROR: GetDirectory - Error getting plugin://plugin.video.wonderfulsubs/search/initial d/1
16:37:28.329 T:18446744071737616672   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.wonderfulsubs/search/initial d/1) failed
16:37:28.577 T:18446744071661156640 WARNING: CSkinInfo: failed to load skin settings

**Comment by Ichijoe2112** [comment]
Well your first problem is Kodi 17.6. Perhaps it's time that you joined the rest of us in 2020, and got on board with v18.6. That said WonderfulSubs hasn't been working there probably since early February. Perhaps with all this Mexican Beer Virus going round now. The Persons behind this Addon might actully find some spare time to update this Addon. Them again probably not, as there hasn't been an update since November of last year.

**Comment by Freelancer95** [comment]
I am using an Amazon Fire TV with Aptoid, v18 isn't an option. I certainly would switch over if there was a clean way of updating my existing install rather than killing all of my settings and favourites. Quite frankly, doing anything with that fucking remote is a bitch, even with adbLink.

**Comment by jryan15** [comment]
It's a wonderful testiment to the program to not update.  Why update when you love what you have and it works?  I hate being forced to update and redo all of my settings especially ones that haven't needed to be touched in years.  Especially when other downstream apps break due to the update.  So annoying.

I get your point if not updating led to the problem, but clearly it didn't so what's your point in bringing it up?  Just feel like dragging a random person down?  Hopefully you feel better now.

**Comment by Ichijoe2112** [comment]
IIRC you can sideload the *.apk directly from the kodi.tv website. And, no updating... Normally should NOT wipe a single thing. Then agan, you are (Or were) 10 point releases back. So I forget if Estuary was already a breakable thing, or no. I personally prefer Confuance. In that simple case. Just update your 'preferred Skin, then carry on.

Sadly as to this, and a great many 'Addons' it's becoming clearer by the day that the best days of Kodi are behind us now. 

This said it does not change the fact (If you were paying any attention), that the last time this Addon saw a Code Update was back in November 2019, almost five months ago now. I haven't seen any recent posts by any of the contributors in like forever. So, it's probably safe to say it's time to find a better alternative.  Netflix, Funimation, Wakanime etc... But, again even the oldest working 'Addons' are dying on their vines right now. With no support in sight. It says something.

**Comment by nalch** [comment]
Wonderful subs migrated to another api version and needs a login for accessing the content it seems.
I created a #134 for those changes so it works again.

So now we have to wait for a maintainer (@DxCx) to check the PR and release a new version or use the pr locally :)

**Comment by DxCx** [comment]
No, this is not dead, please update the addon and check again :)

**Comment by LoopyLucy** [comment]
Thank you!

**Comment by jryan15** [comment]
I installed the new app and now it wants me to log in...   How do I get registered?  I went to the wonderfulsubs site which appears to be under construction, but it gives error 404 codes when trying to get setup.

**Comment by DxCx** [comment]
https://beta.wonderfulsubs.com/signup
