### ISSUE TITLE
Wonderful subs migrated to another api version and needs a login for accessing the content it seems.

### ISSUE THREAD

**Issue by godsavatar** [DxCx/plugin.video.wonderfulsubs#136]
Wonderful subs migrated to another api version and needs a login for accessing the content it seems.
I created a #134 for those changes so it works again.

So now we have to wait for a maintainer (@DxCx) to check the PR and release a new version or use the pr locally :)

_Originally posted by @nalch in https://github.com/DxCx/plugin.video.wonderfulsubs/issues/133#issuecomment-602069309_

**Comment by godsavatar** [comment]
How can i get it to work

**Comment by doko-desuka** [comment]
**EDIT:** See the comments at the bottom.

~~A PR (pull-request) is when someone proposes changes to the code in a repository (a storage). That PR #134 that you quoted is not committed (accepted) to WonderfulSubs yet, it's under review. When it's accepted, you'll be able to update WonderfulSubs from within Kodi, without having to download anything. But you have to wait for the commit to happen.~~

~~If you want to try out that updated version with those changes _before_ they're accepted into this repository, you'll need to download a copy of the repository where those changes are stored.  
The download link is this -- HOWEVER, you have to rename the folder inside this downloadable archive to `plugin.video.wonderfulsubs` (as it will be named `.wonderfulsubs-master` and that won't work in Kodi if you leave it like that): https://github.com/nalch/plugin.video.wonderfulsubs/archive/migrate-to-api-v2.zip~~

~~Once you open the zip file and rename the folder like I mentioned, you can transfer that zip to your Kodi device and do a `Install From Zip` in Kodi.  
**Edit:** and in case the changes are eventually accepted, you can still update WonderfulSubs from within Kodi and it will install over your custom copy.~~

**Comment by MrDoAsILike** [comment]
Thanks for your work. Having said that, I did this and I still can't watch anything. I get a in correct login pop when clicking items/categories to look at/browse. Not sure why.

**Comment by doko-desuka** [comment]
> Thanks for your work.

PR 134 was not made by me if that's what you meant, it's made by @nalch

> ps: I figured out my problem. in the initial page that ooens when you hit the settings button it ask for some login information. Here I put in my WS info and viola, no more incorrect login info popup. hope this helps.

That does help, thanks for confirming to others that it works.

**Comment by doko-desuka** [comment]
You can now close this issue, this official add-on has been updated to support API v2.
