### ISSUE TITLE
Update on MAL after watched doesn't work

### ISSUE THREAD

**Issue by Prometheusx-git** [DxCx/plugin.video.wonderfulsubs#55]
Hi,
the watched status doesn't get an update on MAL after finishing a show.

What i did:
-Login in on MAL with the addon
-Go to MyAnimelist -> Currently Watching
-Choose a show which is for example 7/12
-Play Episode 8 until the end
-Leave the addon
-Start the addon -> go the the show, it is still 7/12

Another try:
-Play Episode 8 and stopp it
-Dialog "do you want to update" -> Yes
-Leave the addon
-Start the addon -> go the the show, it is still 7/12

Tested with 0.0.12

**Comment by SwagOtaku** [comment]
i encountered this after relogging into MAL after seeing this issue.
we'll look into it, thanks

**Comment by SwagOtaku** [comment]
@Prometheusx-git could you test this 
[plugin.video.wonderfulsubs-1-fix-mal-updating.zip](https://github.com/DxCx/plugin.video.wonderfulsubs/files/3125402/plugin.video.wonderfulsubs-1-fix-mal-updating.zip) if this solves issue for you i'll submit a PR

**Comment by Prometheusx-git** [comment]
I have tested the fix. 
Unfortunately it doesn't work for me.
The behavior was the same.

**Comment by SwagOtaku** [comment]
alright thanks, i'll look into it further @Prometheusx-git

**Comment by SasukeShiro** [comment]
@Prometheusx-git i encountered this in version 0.0.9 but i fixed it by logging out, clearing kodi cache, logging back into mal and restarting kodi

**Comment by SasukeShiro** [comment]
Try doing this with [zip swag provided to test]
(https://github.com/DxCx/plugin.video.wonderfulsubs/issues/55#issuecomment-487407313)

**Comment by Prometheusx-git** [comment]
I have tried it again, this time with:
-logout 
-clear cache function from the addon
-restart kodi
-login to mal
and it worked, the episode was updated.
It would be nice, if there was a message in the upper right like "successfully updated MAL" or something.
Maybe you can get an answer from the MAL API for this?

**Comment by DarkLordOfWar** [comment]
program broken 1.0.9, it says inputsream.adaptive is missing
