### ISSUE TITLE
order of the anime My Hero Academia is a little messed up

### ISSUE THREAD

**Issue by JustAguyWhoLikesAnime** [DxCx/plugin.video.wonderfulsubs#65]
when you search for it you see season 1 and then season 2 and 3 but yet if you open season one it has all the episodes of all 3 seasons in it instead of just season 1. not a big issue but it does sorta mess up the watch lists since there is only supposed to be 13 episodes of season 1

**Comment by SwagOtaku** [comment]
@RedNinjaX

**Comment by SasukeShiro** [comment]
@JustAguyWhoLikesAnime this a site issue, not an addon issue. 
It would be better to ask @RedNinjaX on discord since addon grabs from site

**Comment by RedNinjaX** [comment]
I'm actively at work trying fix organization issues of media server side, however I'm currently prioritizing getting the website back up before delving back into that.

**Comment by JustAguyWhoLikesAnime** [comment]
@RedNinjaX ah ok I’m sorry to have bothered ya. Btw love the addon you guys did great

**Comment by RedNinjaX** [comment]
No problem and give SwagOtaku and DxCx all the credit for the add-on 👌
