### ISSUE TITLE
Can’t find eligible sources.

### ISSUE THREAD

**Issue by sprink17** [DxCx/plugin.video.wonderfulsubs#68]
Just recently switched to WS from 9 anime. Watched fine yesterday and today getting the classic “can’t find eligible sources”.
Any ideas?
Btw, loving th new addon!

**Comment by SasukeShiro** [comment]
@sprink17 the discord chat is really helpful in these situation https://discord.gg/yH6ABZM

**Comment by SasukeShiro** [comment]
p.s. the addon is working fine for me

**Comment by SasukeShiro** [comment]
checked discord, the error is because one of the servers on site is not working

**Comment by sprink17** [comment]
Hey thanks for the response. Glad to hear it’s not just on my end.

**Comment by SasukeShiro** [comment]
@RedNinjaX @DxCx @SwagOtaku you guys can close this issue since it has been resolved on site side

**Comment by popsickle123456** [comment]
Still getting "can't find eligible sources" any update?

**Comment by tbob1234** [comment]
The addon is not finding eligible sources
