### ISSUE TITLE
Different Viewmodes needed

### ISSUE THREAD

**Issue by icpryde** [DxCx/plugin.video.wonderfulsubs#76]
Can you add another view called "episodes". Right now everything just falls under "tvshows" for view.

when the episode list is populated that should be under viewmode "episodes". 

Basically we should have the following View modes:

TV Shows (This should be when you are showing lists like Popular, All, etc etc)
Seasons (When you click the show it takes you to the season posters)
Episodes (Once you clickthe season you want to watch it populates the episode list)

These are important when working with skins to get the look you want, right now the entire addon just falls under "tvshows" whether you are looking at episode lists, seasons or tv show lists. This messes with other addons to have a consistent style across kodi.

**Comment by SasukeShiro** [comment]
adding to this could you make them so we can choose like with menu type since 'episodes' and 'seasons' limit the type of viewtypes.
