### ISSUE TITLE
Server/source issues - DASH & HLS vs. 1080p & 720p

### ISSUE THREAD

**Issue by islandtj** [DxCx/plugin.video.wonderfulsubs#84]
I just recently came across this error while attempting to watch Shield Hero. Last week, everything was fine when I had the DASH and HLS server options - the show would play without issue. Today I tried to watch the latest episode and was given the 1080 and 720 server options;  unfortunately either sources resulted in an error.  Would this be attributed to the servers being down?

**Comment by SasukeShiro** [comment]
@islandtj working for me, i get hls, dash, 1080p, 720p, ... sources and they play fine. Check your connection

if your still having issues, the users in discord channel are really helpful https://discord.gg/yH6ABZM

**Comment by icpryde** [comment]
all working for me, just make sure you have preferred quality option set to "Auto HLS"

**Comment by islandtj** [comment]
> @islandtj working for me, i get hls, dash, 1080p, 720p, ... sources and they play fine. Check your connection
> if your still having issues, the users in discord channel are really helpful https://discord.gg/yH6ABZM

Interesting, I did check the connection and removed parental controls on my router and now it works...
In my case, DASH and HLS works with my router parental controls on.  If I want to use the 1080p or 720p - I need to remove the controls.  Not sure if that makes any sense, but at least I found a work around.  Mahalo for the advice and support!

**Comment by islandtj** [comment]
@icpryde, I changed the quality option (it was at 1080p) to Auto HLS and it solved everything (regardless of router control settings)!  You guys are awesome!  Big mahalo for your help :)
