### ISSUE TITLE
Ip blocked using addon

### ISSUE THREAD

**Issue by Evilkind** [DxCx/plugin.video.wonderfulsubs#85]
Hi,
I love the addon but was trying to find out why mine stopped working found I can use it on my phone but not my firestick at home. Found when my phone connected to wifi it was blocked also. It pulls an error no JSon object could be decoded

**Comment by SwagOtaku** [comment]
Try resetting ip by unplugging your router for 5 minutes and restart the router by plugging it back in

**Comment by Shahav** [comment]
Hello
I really need some help here no matter what I do I keep getting the error message, "could not convert string to float." I have tried just about everything; updated browser URL,  updated Kodi,  updated build,  cleared cashe&ect, force close Kodi,  delete & re-enstalled add-on & eat....  I am using Kodi 18.3 on my Android TV Box  with vpn & fast hi speed Wi-F & using repository #0.0.4 with updated version  #0.0.24.  I usually can fix issues pretty easily but this one has me stumped?  I really hope
