### ISSUE TITLE
Cant find eligible sources

### ISSUE THREAD

**Issue by tbob1234** [DxCx/plugin.video.wonderfulsubs#98]
Some shows work and sme do not. Naruto shuppidin dub doesnt work

**Comment by icpryde** [comment]
everything is working on my end, i also tried naruto both dub and sub and its working.

Are you using a MAL account? try logging out and back in and make sure you installed things properly.

**Comment by Xx3GhostHawk9xX** [comment]
I think the reason it says this is because the addon isn't getting the KA Server content for some reason.
