### ISSUE TITLE
Couldn't find eligible sources

### ISSUE THREAD

**Issue by Xx3GhostHawk9xX** [DxCx/plugin.video.wonderfulsubs#99]
I know this only affects some shows so I went on the wonderfulsubs website to test it out. It looks like the dub versions from some shows come only from the KA server and I think the addon isn't connecting to it.

**Comment by Peingod300** [comment]
I am having the same issue, tried several sub shows and got the same error "no eligible sources." Black clover, no game no life, demon slayer, they all did it.  Any idea why the KA server is being a jerk lol

**Comment by Xx3GhostHawk9xX** [comment]
I ended up fixing it by reinstalling the wonderfulsubs addon from this website. It should be V 0.0.23 and I was running an older version for some reason.

**Comment by Shahav** [comment]
Hello DxCx

I've also been having the same issues for about a week now off and on and
even after this last update as well. When i tried to watch some of my dub
shows today with my 14yr. old son on the 4th episode we kept getting error
messages on Seed from then on 😭😖 but later i was watching some of my sub
shows and had no issues playing any of those from start to finish. We are
using kodi 18.3 with a fast vpn on my android box; with high speed
internet. If you need any more information or any error reports just shoot
me an e-mail & let me know. Anyway; what ever you can do to help i would
really appreachiate it cause after my son gets out of school every day we
watch dub anime shows for about an hour or so. I also just wanted to let
you know that i really do 💖  LOVE  the add-on you created & appreciate all
the work that y'all put into maintaining it every day🌟👍👍; so thank you
so very much for that!!! 😀😍😎

Sherry

**Comment by popsickle123456** [comment]
I am having trouble watching dubbed episodes trough the KA server.
